Repository 3BodyProgrammers/sparta-delivery, pull requests merged in 2025-03, with the labels that each got.

#2 가게 API 기능 구현
  requirement/STORE-REQUIREMENT.md
  src/main/java/com/example/spartadelivery/SpartaDeliveryApplication.java
  src/main/java/com/example/spartadelivery/common/entity/BaseEntity.java
  src/main/java/com/example/spartadelivery/common/exception/CustomException.java
  src/main/java/com/example/spartadelivery/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/spartadelivery/config/LocalTimeConverter.java
  src/main/java/com/example/spartadelivery/config/PersistenceConfig.java
  src/main/java/com/example/spartadelivery/domain/menu/dto/response/MenuResponseDto.java
  src/main/java/com/example/spartadelivery/domain/store/controller/StoreController.java
  src/main/java/com/example/spartadelivery/domain/store/dto/request/StoreSaveRequestDto.java
  src/main/java/com/example/spartadelivery/domain/store/dto/request/StoreUpdateRequestDto.java
  src/main/java/com/example/spartadelivery/domain/store/dto/response/StoreDeleteResponseDto.java
  src/main/java/com/example/spartadelivery/domain/store/dto/response/StoreDetailResponseDto.java
  src/main/java/com/example/spartadelivery/domain/store/dto/response/StoreResponseDto.java
  src/main/java/com/example/spartadelivery/domain/store/dto/response/StoreSaveResponseDto.java
  src/main/java/com/example/spartadelivery/domain/store/entity/Store.java
  src/main/java/com/example/spartadelivery/domain/store/repository/StoreRepository.java
  src/main/java/com/example/spartadelivery/domain/store/service/StoreService.java
  src/test/java/com/example/spartadelivery/domain/store/service/StoreServiceTest.java
Labels: documentation, enhancement, needs review

#6 가게 휴일 API 기능 구현
  requirement/STORE-REQUIREMENT.md
  src/main/java/com/example/spartadelivery/config/HolidayConverter.java
  src/main/java/com/example/spartadelivery/config/LocalTimeConverter.java
  src/main/java/com/example/spartadelivery/domain/holiday/controller/StoreHolidayController.java
  src/main/java/com/example/spartadelivery/domain/holiday/dto/request/StoreHolidayRequestDto.java
  src/main/java/com/example/spartadelivery/domain/holiday/enums/Holiday.java
  src/main/java/com/example/spartadelivery/domain/holiday/service/StoreHolidayService.java
  src/main/java/com/example/spartadelivery/domain/store/dto/response/StoreResponseDto.java
  src/main/java/com/example/spartadelivery/domain/store/entity/Store.java
  src/main/java/com/example/spartadelivery/domain/store/service/StoreService.java
  src/test/java/com/example/spartadelivery/domain/holiday/service/StoreHolidayServiceTest.java
  src/test/java/com/example/spartadelivery/domain/store/service/StoreServiceTest.java
Labels: documentation, enhancement, approved

#8 로그인, 유저 API 기능 구현
  .gitignore
  requirement/USER-REQUIREMENT.md
  src/main/java/com/example/spartadelivery/SpartaDeliveryApplication.java
  src/main/java/com/example/spartadelivery/common/annotation/Auth.java
  src/main/java/com/example/spartadelivery/common/dto/AuthUser.java
  src/main/java/com/example/spartadelivery/common/entity/BaseEntity.java
  src/main/java/com/example/spartadelivery/common/exception/CustomException.java
  src/main/java/com/example/spartadelivery/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/spartadelivery/config/AuthUserArgumentResolver.java
  src/main/java/com/example/spartadelivery/config/FilterConfig.java
  src/main/java/com/example/spartadelivery/config/JwtFilter.java
  src/main/java/com/example/spartadelivery/config/JwtUtil.java
  src/main/java/com/example/spartadelivery/config/PasswordEncoder.java
  src/main/java/com/example/spartadelivery/config/PersistenceConfig.java
  src/main/java/com/example/spartadelivery/config/WebConfig.java
  src/main/java/com/example/spartadelivery/domain/auth/controller/AuthController.java
  src/main/java/com/example/spartadelivery/domain/auth/dto/request/SigninRequestDto.java
  src/main/java/com/example/spartadelivery/domain/auth/dto/request/SignupRequestDto.java
  src/main/java/com/example/spartadelivery/domain/auth/dto/response/SigninResponseDto.java
  src/main/java/com/example/spartadelivery/domain/auth/dto/response/SignupResponseDto.java
  src/main/java/com/example/spartadelivery/domain/auth/service/AuthService.java
  src/main/java/com/example/spartadelivery/domain/user/controller/UserController.java
  src/main/java/com/example/spartadelivery/domain/user/dto/request/UserDeleteRequestDto.java
  src/main/java/com/example/spartadelivery/domain/user/dto/request/UserUpdateRequestDto.java
  src/main/java/com/example/spartadelivery/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/spartadelivery/domain/user/entity/User.java
  src/main/java/com/example/spartadelivery/domain/user/enums/UserRole.java
  src/main/java/com/example/spartadelivery/domain/user/repository/UserRepository.java
  src/main/java/com/example/spartadelivery/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/example/spartadelivery/domain/auth/service/AuthServiceTest.java
  src/test/java/com/example/spartadelivery/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/example/spartadelivery/domain/user/service/UserServiceTest.java
Labels: documentation, enhancement, approved

#9 가게 API 기능 수정
  src/main/java/com/example/spartadelivery/common/annotation/Owner.java
  src/main/java/com/example/spartadelivery/common/aop/OwnerAccessAspect.java
  src/main/java/com/example/spartadelivery/config/HolidayConverter.java
  src/main/java/com/example/spartadelivery/config/LocalTimeConverter.java
  src/main/java/com/example/spartadelivery/domain/holiday/controller/StoreHolidayController.java
  src/main/java/com/example/spartadelivery/domain/holiday/dto/request/StoreHolidayRequestDto.java
  src/main/java/com/example/spartadelivery/domain/holiday/enums/Holiday.java
  src/main/java/com/example/spartadelivery/domain/holiday/service/StoreHolidayService.java
  src/main/java/com/example/spartadelivery/domain/store/controller/StoreController.java
  src/main/java/com/example/spartadelivery/domain/store/dto/request/StoreSaveRequestDto.java
  src/main/java/com/example/spartadelivery/domain/store/dto/request/StoreUpdateRequestDto.java
  src/main/java/com/example/spartadelivery/domain/store/dto/response/StoreResponseDto.java
  src/main/java/com/example/spartadelivery/domain/store/entity/Store.java
  src/main/java/com/example/spartadelivery/domain/store/repository/StoreRepository.java
  src/main/java/com/example/spartadelivery/domain/store/service/StoreService.java
  src/main/java/com/example/spartadelivery/domain/user/entity/User.java
  src/test/java/com/example/spartadelivery/domain/holiday/service/StoreHolidayServiceTest.java
  src/test/java/com/example/spartadelivery/domain/store/service/StoreServiceTest.java
Labels: documentation, enhancement, approved

#17 가게 대시보드 API 구현
  requirement/STOREDASHBOARD-REQUIREMENT.md
  src/main/java/com/example/spartadelivery/config/LocalTimeConverter.java
  src/main/java/com/example/spartadelivery/domain/menu/dto/response/MenuUpdateResponseDto.java
  src/main/java/com/example/spartadelivery/domain/menu/entity/Menu.java
  src/main/java/com/example/spartadelivery/domain/order/dto/response/OrderStatusUpdateResponseDto.java
  src/main/java/com/example/spartadelivery/domain/order/repository/OrderRepository.java
  src/main/java/com/example/spartadelivery/domain/order/service/OrderGetService.java
  src/main/java/com/example/spartadelivery/domain/order/service/OrderService.java
  src/main/java/com/example/spartadelivery/domain/review/service/ReviewService.java
  src/main/java/com/example/spartadelivery/domain/store/dto/response/StoreResponseDto.java
  src/main/java/com/example/spartadelivery/domain/store/dto/response/StoreSaveResponseDto.java
  src/main/java/com/example/spartadelivery/domain/storedashboard/controller/StoreDashBoardController.java
  src/main/java/com/example/spartadelivery/domain/storedashboard/dto/StoreDashBoardDayResponseDto.java
  src/main/java/com/example/spartadelivery/domain/storedashboard/dto/StoreDashBoardPeriodResponseDto.java
  src/main/java/com/example/spartadelivery/domain/storedashboard/service/StoreDashBoardService.java
  src/test/java/com/example/spartadelivery/domain/menu/service/MenuServiceTest.java
Labels: documentation, enhancement
